### ISSUE TITLE
[JOSS review] Dependency issue Matplotlib

### ISSUE THREAD

**Issue by SunyongKwon** [qiangyicheng/flory#19]
A few examples require the `Matplotlib` package for visualization.
Please consider adding `Matplotlib` in the installation requirement, so that the users run examples without facing issues.

**Comment by qiangyicheng** [comment]
Thank you for the helpful suggestion.  We did not include `Matplotlib` since it is bulky and not directly referenced by the main functionality of our package. Therefore we chose to treat it as an optional dependency that can be installed by a `dev` option. We have revised `README.md` to clarify this, and provided options `example`, `test` and `doc` to choose among different groups of optional dependencies.
